# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cabral's Blog
email: webmaster@cabral.eti.br
description: > # this means to ignore newlines until "baseurl:"
  No description yet. Still trying do figure out what this is.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cabral.eti.br" # the base hostname & protocol for your site
twitter_username: cabral404
github_username:  cabral404

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
